### ISSUE TITLE
Unable to compile with libctru-1.0.0

### ISSUE THREAD

**Issue by gemarcano** [phase/oot3dhax_installer#13]
It seems that the code was built to use libcrtu-0.6.0. When trying to build the application, I get errors like:

```
filesystem.c
arm-none-eabi-gcc -MMD -MP -MF /mnt/Media/home/gabriel/Projects/3ds/oot3dhax_installer/build/filesystem.d -g -Wall -O2 -mword-relocations -fomit-frame-pointer -ffast-math -march=armv6k -mtune=mpcore -mfloat-abi=hard -I/mnt/Media/home/gabriel/Projects/3ds/oot3dhax_installer/include -I/opt/devkitpro/libctru/include -I/mnt/Media/home/gabriel/Projects/3ds/oot3dhax_installer/build -DARM11 -D_3DS -c /mnt/Media/home/gabriel/Projects/3ds/oot3dhax_installer/source/filesystem.c -o filesystem.o 
In file included from /mnt/Media/home/gabriel/Projects/3ds/oot3dhax_installer/source/filesystem.c:6:0:
/mnt/Media/home/gabriel/Projects/3ds/oot3dhax_installer/source/filesystem.h:5:8: error: unknown type name 'FS_archive'
 extern FS_archive saveGameArchive, sdmcArchive;
        ^
```

I would try to convert this over, but I am still learning about 3DS homebrewing (read: I'm not familiar with the libraries and system facilities available yet).

**Comment by phase** [comment]
In the latest version, `FS_archive` was changed to `FS_Archive`. :disappointed: I'll get this fixed _soon_, or you can submit a PR. An easy way to figure out what is wrong is to look through the [ctrulib source](https://github.com/smealum/ctrulib), that's how I found [this](https://github.com/smealum/ctrulib/blob/master/libctru/include/3ds/services/fs.h#L233).

**Comment by gemarcano** [comment]
Yes, I had found `fs.h` and checked how it changed (the struct isn't quite the same...). As you probably know, there are other issues :smile: . I may try to see what I can do as a forceful introduction into 3ds development, haha.
